### ISSUE TITLE
登录失败，提示要验证码了

### ISSUE THREAD

**Issue by liuliangcan** [xjq7/lc-helper#2]
![image](https://github.com/xjq7/lc-helper/assets/3946606/059ba450-990d-4049-ae44-8324b18d329b)

**Comment by xjq7** [comment]
@liuliangcan 账号密码登录做了改动吧，得重新对接下力扣登录了

**Comment by xjq7** [comment]
@liuliangcan 更新了下，现在不用账号密码登录了，需要去力扣站点下登录获取 session 设置到 github action 变量中，你可以参照我 README 文档的修改试试
